# This is a sample build configuration for C++ ▒ Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: gcc:6.1
image: rootproject/root-cc7

pipelines:
  default:
     - step:
        name: Build and Test agana
        #caches:
        #  - rootana-folders
        script: # Modify the commands below to build your repository.
            - git submodule update --init
            - export ROOT_INCLUDE_PATH=/usr/include/root
            - yum install -y lesstif-devel libXmu libXmu-devel eos-* valgrind
            - . agconfig.sh
            - cd ${AGRELEASE}
            - make
            #We are running with limited CPU time per month... don't run RunChecker (run that on gitlab)
            #- cd ..
            #- . agconfig.sh clean
            #- cd scripts/gitChecker
            #- ./RunChecker.sh

     - step:
        name: Update rootana and build
        script: 
            - git submodule update --init
            - export ROOT_INCLUDE_PATH=/usr/include/root
            - yum install -y lesstif-devel libXmu libXmu-devel eos-* valgrind
            - . agconfig.sh
            - RANA=`git submodule update --remote | wc -l`
            - echo ${RANA}
            #If the version is the same, quit... nothing to do here
            - if [ ${RANA} -eq 0 ]; then exit; fi
            - make clean
            - make
            #If compiling was successful... push the new version of rootana to agdaq repo
            - git remote set-url origin git@bitbucket.org:/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}.git
            - git config user.name "bitbucket CI"
            - git remote -v 
            - git add rootana
            - SUMMARY=`git submodule summary`
            - git commit -m "[skip ci] Update rootana (agana compiles ok with this new version)
            
${SUMMARY}"
            - git push origin

definitions:
  caches:
    rootana-folders: rootana
