#
# Rules for building aged files
#
# 2017-08-08 - Phil Harvey
#

.KEEP_STATE:

HDRS        = $(wildcard include/*.h)
CXX_FILES   = $(wildcard src/*.cxx)
OBJS        = $(patsubst src/%.cxx,obj/%.o,$(CXX_FILES))

libaged.so: $(OBJS)
	$(LDCC) -fPIC -shared $(LDFLAGS) $(OBJS) $(XLIBS) $(LIBS) $(ROOTLIBS) -o libaged.so

obj/%.o: src/%.cxx include/%.h $(HDRS)
	$(CXX) $(CXXFLAGS) $(INCLUDE) $(XFLAGS) $(ROOTFLAGS) -o $@ -c $<
