#
# Rules for building aged files
#
# 2017-08-08 - Phil Harvey
#

.KEEP_STATE:

HDRS        = $(wildcard *.h)
CXX_FILES   = $(wildcard *.cxx)
OBJS        = $(patsubst %.cxx,%.o,$(CXX_FILES))

libaged.so: $(OBJS)
	$(LDCC) -fPIC -shared $(LDFLAGS) $(OBJS) $(XLIBS) $(LIBS) $(ROOTLIBS) -o libaged.so

%.o: %.cxx %.h $(HDRS)
	$(CXX) $(CXXFLAGS) $(INCLUDE) $(XFLAGS) $(ROOTFLAGS) -o $@ -c $<
