
/gasModelParameters/heed/heedinterface/addparticle e- 0. 0.001
/gasModelParameters/heed/heedinterface/addparticle gamma 0. 10000000

/gasModelParameters/heed/heedonly/addparticle e- 0.1 100000.
/gasModelParameters/heed/heedonly/addparticle e+ 1000. 100000.
/gasModelParameters/heed/heedonly/addparticle p 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu+ 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu- 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle mu 1000. 1000000.
/gasModelParameters/heed/heedonly/addparticle pi+ 100. 1000000.
/gasModelParameters/heed/heedonly/addparticle pi- 100. 1000000.

/gasModelParameters/heed/drift 1
/gasModelParameters/heed/driftRKF 1
/gasModelParameters/heed/trackmicroscopic 0
/gasModelParameters/heed/createAval 0
/gasModelParameters/heed/visualizechamber 1
/gasModelParameters/heed/visualizesignals 1
/gasModelParameters/heed/visualizefield 1

#/run/numberOfThreads 1
#/control/cout/ignoreThreadsExcept 0
/control/cout/setCoutFile output.dmp
/AGTPC/phys/setLowLimitE 20. eV
#/AGTPC/phys/InitializePhysics emlivermore
/AGTPC/phys/InitializePhysics emstandard_opt0
/AGTPC/phys/AddParametrisation
/process/em/AddPAIRegion all DriftRegion PAIphoton

/random/setSeeds 18061985 10081985
/run/initialize

####################################
############ Verbosities ###########
####################################
/tracking/verbose 1
/run/verbose 1
/event/verbose 0

####################################
######### Primary Generator ########
####################################
/AGTPC/setRunType 6

####################################
/run/beamOn 1
