# Open the viewer driver
/vis/open OGL 600x600-0+0
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Set initial orientation
#/vis/viewer/set/viewpointThetaPhi 280 90
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/zoom 3
#
# Draw smooth trajectories 
/vis/scene/add/trajectories smooth
#
# Decorations
# Axes, scale, etc.
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
#/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! ALPHA-g TPC
#
# To get nice view
/vis/viewer/set/style surface
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose errors

/control/verbose 1

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set pi+ blue
/vis/modeling/trajectories/drawByParticleID-0/set pi- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set e- magenta

/vis/scene/add/hits

/AGTPC/setRunName vis