####################################
########### Visualization ##########
####################################
/vis/open OGL 600x600-0+0
# Draw geometry:
/vis/drawVolume
# Set initial orientation
#/vis/viewer/set/viewpointThetaPhi 280 90
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/zoom 3
# Scene
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 1
# Decorations
# Axes, scale, etc.
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
#/vis/scene/add/date    # Date stamp
/vis/scene/add/logo2D  # Simple logo
# Name
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! ALPHA-g rTPC
# Trajectories
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add pi+
/vis/filtering/trajectories/particleFilter-0/add pi-
/vis/filtering/trajectories/particleFilter-0/add e+
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set pi+ blue
/vis/modeling/trajectories/drawByParticleID-0/set pi- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set e- magenta
/tracking/storeTrajectory 1
